"""empty message

Revision ID: e94c09338816
Revises: e516f5e769df
Create Date: 2022-05-05 10:46:28.119040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e94c09338816'
down_revision = 'e516f5e769df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
